[package]
name = "find-git-dirs"
version = "0.5.0"
edition = "2021"

[dependencies]
anyhow = "1.0"
clap = { version = "4.5", features = ["derive"] }
crossterm = "0.27"
crossbeam-channel = "0.5"
ignore = "0.4"
rayon = "1.10"
ratatui = "0.28"
